[[redirects]]
  from = "/products"
  to = "http://productsfetch.herokuapp.com/"
  status = 200

[[redirects]]
  from = "/signup"
  to = "/product/cart"
  status = 200

[[redirects]]
  from = "/*"
  to = "/"
  status = 200