 [[redirects]]
  from = "/products"
  to = "http://productsfetch.herokuapp.com/products/?format=json"
  status = 200
  force = true
  headers = {Access-Control-Allow-Origin = "*"}


[[redirects]]
  from = "/*"
  to = "/"
  status = 200

